version: '3'
services:
  postgres:
    image: postgres:13
    container_name: taskstack-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB-PASSWORD:-postgres}
    ports:
    - ${DB_PORT:-5432}:5432
